# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.3"

pre_release = false

preface = """\
"""

[notes]
    [notes.installer]
        title = "Installer Turingrk1 image"


        description = """\
When upgrading using `talosctl upgrade -i` a `-rk3588` can be added to the install image tag to get the image
with the rk3588 extension. This eliminates the need for defining the extension in the machine config.

Please remove the extension from the machine config before using 
`talosctl upgrade -i ghcr.io/nberlee/installer:v1.6.4-rk3588`
"""
    [notes.updates]
        title = "Component Updates"


        description = """\
containerd: 1.7.13
runc: 1.1.12
Linux: 6.6.15

See [CVE-2024-21626](https://github.com/opencontainers/runc/security/advisories/GHSA-xr7r-f8xq-vfvv) for the runc update.

Talos is built with Go 1.21.6.
"""


[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
