# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.1"

pre_release = false

preface = """\
"""

[notes]
    [note.turing-rk1-hardware]
        title = "Turing RK1 hardware support"
        description = """\
 - Fix for corrupted tagged vlan frames
 - USB hotplug support
 - Increased Network troughput
 - Increased boot performance
"""
    [notes.updates]
        title = "Component Updates"


        description = """\
Linux: 6.6.12
containerd: 1.7.11
u-boot: 2024-01

Talos is built with Go 1.21.6.
"""


[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
