# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.4"

pre_release = false

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"


        description = """\
Kubernetes: 1.29.2
Linux: 6.6.17
arm-trusted-firmware: 2.10.2

Talos is built with Go 1.21.6.
"""

   [notes.fanspeed]
        title = "Turing RK1: fan speed"
        description = """\
The fanspeed curve has been adjusted to be more idle in lite cpu load utilization scenarios.
"""

    [notes.usb2]
         title = "Turing RK1: USB2"
         description = """\
USB2 support has been restored. It was broken in Talos 1.6.4.
"""

    [notes.k8supgrade]
        title = "Kubernetes Upgrade"
        description = """\
The command `talosctl upgrade-k8s` now supports specifying custom image references for Kubernetes components via `--*-image` flags.
The default behavior is unchanged, and the flags are optional.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
