name: Talos RK Images

on:
  workflow_dispatch:

env:
  ORIGIN_REPO: siderolabs/talos
  ORIGIN_TAG: v1.8.3
  SBC_TAG: v1.8.3
  RK3588_TAG: v1.8.3
  PUBLISH_TAG: v1.8.3-6.12
  PUSH_REGISTRY: registry.camsab.me:443/talos
  USERNAME: talos
  LINUX_TOOLS: 2.40.2@sha256:3c3d2c76290fe1133d2472b01707b69bfdcc5b804a49e6370110001e23fa252a
  ISCSI_TOOLS: v0.1.6@sha256:0c1ca0576ea6a5245b830b1d6093feafb751745a8efb0448bd170c068c88541f
jobs:
  talos-build:
    runs-on: home-runners
    container:
      #### WARNING this image should be ${{ env.REGISTRY }}/imager:${{ env.PUBLISH_TAG }} but seems jobs can't access env so need to put it here manually 
      image: registry.camsab.me:443/talos/imager:v1.8.3-77fe65d17c
    permissions:
      contents: read # read the repository
    steps:
      - name: Build an turing-rk1 flashable image
        run: |
          /bin/imager metal --arch arm64 --base-installer-image ${{ env.REGISTRY}}/:${{ env.PUBLISH_TAG}}-nosbclayer --system-extension-image ${{ env.REGISTRY}}/rk3588:${{ env.RK3588_TAG }} --system-extension-image ghcr.io/siderolabs/util-linux-tools:${{ env.LINUX_TOOLS}} --system-extension-image ghcr.io/siderolabs/iscsi-tools:${{ env.ISCSI_TOOLS}} --overlay-image ${{ env.REGISTRY}}/sbc-turingrk1:${{ env.SBC_TAG }} --overlay-name=turingrk1
      - name: Build an turing-rk1 installer
        run: |
          /bin/imager installer --arch arm64 --base-installer-image ${{ env.REGISTRY}}/installer:${{ env.PUBLISH_TAG}}-nosbclayer --system-extension-image ${{ env.REGISTRY}}/rk3588:${{ env.RK3588_TAG }}  --system-extension-image ghcr.io/siderolabs/util-linux-tools:${{ env.LINUX_TOOLS}} --system-extension-image ghcr.io/siderolabs/iscsi-tools:${{ env.ISCSI_TOOLS}} --overlay-image ${{ env.REGISTRY}}/sbc-turingrk1:${{ env.SBC_TAG }} --overlay-name=turingrk1
          apk add crane
          crane push /out/installer-arm64.tar ${{ env.PUSH_REGISTRY}}/installer:${{ env.PUBLISH_TAG }}-rk3588
  talos-upload:
    runs-on: home-runners
    needs: [talos-build]
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: image-turing-rk1
          path: /out/*.raw.zst
        