name: Talos RK Images

on:
  workflow_dispatch:

env:
  ORIGIN_REPO: smira/talos
  ORIGIN_TAG: backports/v1.8.2
  KERNEL_TAG: v1.8.1-6-g9f2d546
  SBC_TAG: v1.8.1
  RK3588_TAG: v1.8.1-6-gd38ec69
  REGISTRY: docker-registry.registry.svc.cluster.local:5000
  USERNAME: talos
jobs:
          
  talos-build:
    runs-on: home-runners
    container:
      image: ghcr.io/nberlee/imager:v1.8.2-2e003697a7
    permissions:
      contents: read # read the repository
    steps:
      - name: Build an turing-rk1 flashable image
        run: |
          /bin/imager metal --arch arm64 --base-installer-image ghcr.io/nberlee/installer:v1.8.2-2e003697a7-nosbclayer --system-extension-image ghcr.io/nberlee/rk3588:${{ env.RK3588_TAG }} --overlay-image ghcr.io/nberlee/sbc-turingrk1:${{ env.SBC_TAG }} --overlay-name=turingrk1

      - name: Build an turing-rk1 installer
        run: |
            /bin/imager installer --arch arm64 --base-installer-image ghcr.io/nberlee/installer:v1.8.2-2e003697a7-nosbclayer --system-extension-image ghcr.io/nberlee/rk3588:${{ env.RK3588_TAG }} --overlay-image ghcr.io/nberlee/sbc-turingrk1:${{ env.SBC_TAG }} --overlay-name=turingrk1
            curl -sL "https://github.com/google/go-containerregistry/releases/download/v0.20.2/go-containerregistry_$(uname -s)_$(uname -m).tar.gz" | tar -zxv -C /usr/local/bin/ crane
            crane push _out/installer-arm64.tar docker-registry.registry.svc.cluster.local:5000/talos/installer:v1.8.2-2e003697a7-rk3588
        
      - uses: actions/upload-artifact@v3
        with:
          name: image-turing-rk1
          path: _out/*.raw.xz
          if-no-files-found: error
        