name: Talos Image

on:
  workflow_dispatch:
  #push:
  #  branches: [ 'release-*' ]
  #  tags:
  #    - "v*"

env:
  ORIGIN_REPO: smira/talos
  ORIGIN_TAG: backports/v1.8.2
  KERNEL_TAG: v1.8.1-6-g9f2d546
  SBC_TAG: v1.8.1
  RK3588_TAG: v1.8.1-6-gd38ec69

jobs:
  talos-build-at-home:
    runs-on: home-runners
    container:
      image: gcr.io/kaniko-project/executor:debug # the kaniko image

    permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read

    steps:
      - name: Build and Push Image to docker registry with kaniko
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://quay.io/v2/": {
                "auth": "$(echo -n "${{ secrets.QUAY_USER }}:${{ secrets.QUAY_PASS }}" | base64 )"
              }
            }
          }
          EOF

          /kaniko/executor --dockerfile="Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination="$DOCKER_IMAGE_NAME:${{ github.ref_name }}" \
            --cache=true --cache-copy-layers \
            --target=installer
            --push-retry 5 
    env: 
      GIT_USERNAME: ${{ github.actor }}
      GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_IMAGE_NAME: "quay.io/camillo/talos/installer"