
name: Local registry test

on:
  workflow_dispatch:

jobs:
  talos-build:
    runs-on: home-runners

    permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read

    steps:
      - name: Install make
        run: sudo apt-get install make

      - uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=actions-runner
            replicas=1
            nodeselector=model=rk1
            limits.memory=2G
            limits.ephemeral-storage=1G
          buildkitd-config-inline: |
            ["docker-registry.registry.svc.cluster.local"]
              http = true
              insecure = true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ORIGIN_REPO }}
          ref: ${{ env.ORIGIN_TAG }}
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true

      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker-registry.registry.svc.cluster.local:5000/name/app:latest